#!/bin/sh

rn_init () {
  # Set up color variables for command line output.
  r='\033[0;31m';g='\033[0;32m';y='\033[0;33m';b='\033[0;34m';m='\033[0;35m';c='\033[0;36m';w='\033[0m'
  # Some repeatable strings and interaction commands.
  YESNO () { read -p " yY(es)/nN(o): " -n 1 -r ; printf "\n" ; }
  ASK () { printf "\nDo you want to ${g}${1}${w}?" ; }
  CONFIRM () { ASK "${1}" ; YESNO ; }
  MULTICHOICE () { ASK "${1}" ; read -p " (${2}): " -n 1 -r ; printf "\n" ; }
  SKIP () { printf "\nOk. ${g}Skipped${w} for now.\n" ; }
  ABORD () { printf "\n${g}Abord script${w} for now.\n" ; exit 1 ; }
  NO_ARG () { printf "\n${r}Missing argument(s)${w}." ; }
  INPROGRESS () { printf "This feature is unsupported yet but in progress." ; ABORD ; }
  COMPLETED () { printf "\n${1} ${g}has been completed.${w}\n\n" ; }
  WRONGINPUT () { printf "Wrong input." ; ABORD ; }
  STOPERROR="${r}Error: Stopped (di) Drupal Install command!${w}"
  PRESSENTER="[Press ${g}ENTER${w} or ${g}RETURN${w} to go ahead. PRESS ${g}CTRL/C${w} to stop]"
  EXECUTE () {
    CONFIRM $1
    if [ "${REPLY}" =~ ^([yY][eE][sS]|[yY])$ ] ; then
      $2 ; COMPLETED $1
    else
      SKIP
  }
}

rn_run () {
  if [ $# -lt 2 ] ; then
    NO_ARG ; ABORD
  else
    EXECUTE "rename files recursively" rn_files;
    EXECUTE "replace pattern in strings recursively." rn_strings;
  fi
}

rn_files () {
  unset FILENAME;
  unset NEW_FILENAME;
  find . -type f -name "*${1}*" | while read FILENAME ; do
    NEW_FILENAME="$(echo ${FILENAME} | sed -e "s/${1}/${2}/g")";
    mv "${FILENAME}" "${NEW_FILENAME}";
  done
}

rn_strings () {
  find . -type f -exec sed -i "s/${1}/${2}/g w /dev/stdout" '{}' \;
}

rn_quit () { 
  printf "\n${g}Done!${w}\n\n" ; exit 0 
}

rn_init
rn_run
rn_quit
